on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Zip the binary
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          zip -r extension-${TAG_NAME}.zip dist/
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension-${{ env.TAG_NAME }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension-${{ env.TAG_NAME }}.zip
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.BILI_WEB_EXTENSION }}
