on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm@11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Zip the binary
        shell: bash
        run: |
          zip -r "extension-${GITHUB_REF_NAME}.zip" dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension-${{ env.GITHUB_REF_NAME }}.zip
          tag_name: ${{ env.GITHUB_REF_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.BILI_WEB_EXTENSION }}
